extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  jaeger_thrift:
    url: "http://tracer:14268/api/traces"

  prometheus:
    endpoint: "0.0.0.0:9102"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_thrift]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

  extensions: [health_check]
